services:
  angular:
    build:
      context: ./frontend
    platform: linux/amd64  # or use linux/arm64 for native Apple Silicon builds
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  pocketbase:
    build:
      context: ./backend
    platform: linux/amd64  # pocketbase is distributed as amd64 binaries
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/pb/pb_data
    restart: unless-stopped
