services:
  angular:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  pocketbase:
    build:
      context: ./backend
    ports:
      - "8090:8090"
    volumes:
      - ./backend:/pb
      - ./backend/migrations:/pb/migrations
      - ./backend/pb_data:/pb/pb_data
    restart: unless-stopped
