name: lint-test-coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (verify only)
        run: npm run lint

  lint-prettier:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier verify
        run: |
          echo "Running Prettier verification (not fixing automatically)..."
          npm run prettier:verify || (
            echo "Prettier found formatting issues. Please run 'npm run prettier:fix' locally to fix them." && exit 1
          )

  test-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome for Karma tests
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV

      - name: Run tests with coverage
        run: npx ng test --watch=false --browsers=ChromeHeadlessCI --code-coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./frontend/coverage/

      - name: Upload coverage to GitHub (Cobertura)
        uses: actions/upload-artifact@v4
        with:
          name: cobertura-coverage
          path: ./frontend/coverage/cobertura-coverage.xml
